using gettext to localize messages
* new make rule to create pot file: 'make pot'

diff --git a/usr/bin/docpatch b/usr/bin/docpatch
--- a/usr/bin/docpatch
+++ b/usr/bin/docpatch
@@ -40,14 +40,15 @@ COMMANDS[1]="build"
 COMMANDS[2]="create"
 
 ## Descriptions of supported commands
-COMMAND_BUILD="Build repository."
-COMMAND_CREATE="Produce pretty output from source."
+COMMAND_BUILD=$"Build repository."
+COMMAND_CREATE=$"Produce pretty output from source."
 
 ## Required main command
 COMMAND=""
 
 ## Optional sub command
 SUB_COMMAND=""
+
 
 
 ##
@@ -92,135 +93,135 @@ if [ ! -r "/usr/share/${PROJECT_NAME}/${PROJECT_NAME}.inc" ]; then
 ## Normal exit
 trap 'exit 0' 0
 ## SIGHUB
-trap 'lognotice "Caught SIGHUB, but nothing to do."' 1
+trap 'lognotice $"Caught SIGHUB, but nothing to do."' 1
 ## SIGINT
-trap 'logwarning "Caught SIGINT." ; abort 102' 2
+trap 'logwarning $"Caught SIGINT." ; abort 102' 2
 ## SIGQUIT
-trap 'logwarning "Caught SIGQUIT." ; abort 103' 3
+trap 'logwarning $"Caught SIGQUIT." ; abort 103' 3
 ## SIGTERM
-trap 'logwarning "Caught SIGTERM." ; abort 115' 15
+trap 'logwarning $"Caught SIGTERM." ; abort 115' 15
 
 
 ## Process given options and arguments
-loginfo "Process given options and arguments..."
+loginfo $"Process given options and arguments..."
 ARGS=`"$GETOPT" \
 -o qvVDhef:r:R:s:St \
 --long help,version,license,embed,embedded,format:,not-smart,output:,rev:,revision:,repo:,repository:,sign,simple,toc -- "$@" 2> /dev/null`
 
 if [ $? != 0 -o "$#" = 0 ]; then
-    logwarning "Bad request."
+    logwarning $"Bad request."
     printUsage
     abort 1;
   fi
 
 eval set -- "$ARGS"
 
-logdebug "Processed."
+logdebug $"Processed."
 
 
 ## Match options and arguments
-loginfo "Matching options and arguments..."
+loginfo $"Matching options and arguments..."
 
 while true ; do
     case "$1" in
     # Output:
         -q)
           VERBOSITY=$LOG_NONE
-          logdebug "Set verbosity: $VERBOSITY"
+          logdebug $"Set verbosity: $VERBOSITY"
           shift;;
         -v)
           VERBOSITY=$(($LOG_FATAL | $LOG_ERROR | $LOG_WARNING | $LOG_NOTICE))
-          logdebug "Set verbosity: $VERBOSITY"
+          logdebug $"Set verbosity: $VERBOSITY"
           shift;;
         -V)
           VERBOSITY=$(($LOG_ALL & ~$LOG_DEBUG))
-          logdebug "Set verbosity: $VERBOSITY"
+          logdebug $"Set verbosity: $VERBOSITY"
           shift;;
         -D)
           VERBOSITY=$LOG_ALL;
-          logdebug "Set verbosity: $VERBOSITY"
+          logdebug $"Set verbosity: $VERBOSITY"
           shift;;
     # Information:
         -h|--help)
-          logdebug "Set PRINT_USAGE=1"
+          logdebug $"Set option: Print usage."
           PRINT_USAGE=1;
           shift;;
         --version)
-          logdebug "Set PRINT_VERSION=1"
+          logdebug $"Set option: Print version."
           PRINT_VERSION=1;
           shift;;
         --license)
-          logdebug "Set PRINT_LICENSE=1"
+          logdebug $"Set option: Print license."
           PRINT_LICENSE=1;
           shift;;
     # Options:
         -e|--embed|--embedded)
-          logdebug "Set EMBEDDED=1"
-          EMBEDDED=1;
+          logdebug $"Set option: Create embedded output."
+          EMBED=1;
           shift 1;;
         -S|--simple|--not-smart)
-          logdebug "Set SIMPLE=1"
+          logdebug $"Set option: Create simplified output."
           SIMPLE=1;
           shift 1;;
         -f|--format|--output)
-          logdebug "Set OUTPUT_FORMAT=$2"
+          logdebug $"Set option: Output format is '${2}'."
           OUTPUT_FORMAT="$2";
           shift 2;;
         -r|--rev|--revision)
-          logdebug "Set ARG_REVISION=$2"
+          logdebug $"Set option: Revision is '${2}'."
           ARG_REVISION="$2";
           shift 2;;
         -R|--repo|--repository)
-          logdebug "Set REPOSITORY=$2"
+          logdebug $"Set option: Repository is '${2}'."
           REPOSITORY="$2";
           shift 2;;
         -s|--sign)
-          logdebug "Set SIGN=1"
+          logdebug $"Set option: Sign tags."
           SIGN=1;
           shift;;
         -t|--toc)
-          logdebug "Set TOC=1"
+          logdebug $"Set option: Create table of contents."
           TOC=1;
           shift;;
         --)
           shift;
           break;;
         *)
-          lognotice "Unkown option ${1}."
+          lognotice $"Unkown option '${1}'."
           printUsage
           abort 2;;
   esac
 done
 
-logdebug "Matched."
+logdebug $"Matched."
 
 
 ## Try to match commands with given options
-loginfo "Trying to match commands with given options..."
+loginfo $"Trying to match commands with given options..."
 
-loginfo "Trying to match main command..."
+loginfo $"Trying to match main command..."
 for x in "$@"; do
     for y in "${COMMANDS[@]}"; do
         if [ "$x" == "$y" ]; then
             COMMAND="$x"
-            logdebug "Main command is $COMMAND."
+            logdebug $"Main command is $COMMAND."
             break 2
           fi
       done
   done
 
-loginfo "Trying to match sub command..."
+loginfo $"Trying to match sub command..."
 if [ -n "$2" -a "$2" != " " ]; then
     SUB_COMMAND="$2"
-    logdebug "Sub command is $SUB_COMMAND."
+    logdebug $"Sub command is $SUB_COMMAND."
   else
-    logdebug "There is no sub command."
+    logdebug $"There is no sub command."
   fi
 
 
 ## Include command specific file
 if [ -z "$COMMAND" ]; then
-    logdebug "No command found."
+    logdebug $"No main command found."
   else
     includeCommand "$COMMAND" || abort 3
   fi
@@ -253,7 +254,7 @@ applyNiceLevel || abort 4
 
 ## Call command specific main method
 if [ -z "$COMMAND" ]; then
-    lognotice "Nothing to do."
+    lognotice $"Nothing to do."
     printUsage
     abort 5
   else
diff --git a/usr/share/docpatch/help b/usr/share/docpatch/help
--- a/usr/share/docpatch/help
+++ b/usr/share/docpatch/help
@@ -25,29 +25,29 @@
 
 ## Main method
 function main {
-  loginfo "How can I help you?"
+    loginfo $"How can I help you?"
 
-  local manpage="$PROJECT_NAME"
+    local manpage="$PROJECT_NAME"
 
-  if [ -n "$SUB_COMMAND" ]; then
-      manpage="$manpage-${SUB_COMMAND}"
+    if [ -n "$SUB_COMMAND" ]; then
+        manpage="$manpage-${SUB_COMMAND}"
     fi
 
-  logdebug "Calling man page..."
-  "$MAN" "$manpage"
-  if [ $? -gt 0 ]; then
-      logwarning "Application for man pages returned with an error."
-      logerror "Cannot show man page for ${manpage}."
-      abort 1
+    logdebug $"Calling man page..."
+    "$MAN" "$manpage"
+    if [ $? -gt 0 ]; then
+        logwarning $"Application for man pages returned with an error."
+        logerror $"Cannot show man page for '${manpage}'."
+        abort 1
     fi
-  logdebug "Man page called."
+    logdebug $"Man page called."
 }
 
 
 ## Prints command specific options.
 function printCommandOptions {
-  loginfo "Printing command specific options..."
-  prntLn "    No options"
-  logdebug "Options printed."
-  return 0
+    loginfo $"Printing command specific options..."
+    prntLn $"    No options"
+    logdebug $"Options printed."
+    return 0
 }
